# Generated by Django 3.0.3 on 2020-02-17 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='%d-%m-%y'),
            preserve_default=False,
        ),
    ]
