# Generated by Django 3.0.3 on 2020-02-27 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owners', '0003_auto_20200227_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='users',
        ),
        migrations.AddField(
            model_name='permissions',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
