# Generated by Django 3.0.3 on 2020-02-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_auto_20200227_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
