# Generated by Django 3.0.3 on 2020-03-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0007_delete_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
