# Generated by Django 3.0.3 on 2020-02-15 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('owners', '0002_auto_20200205_0003'),
        ('shops', '0003_productaddtoshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_shops', to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productaddtoshop',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productaddtoshop',
            name='shop',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='owners.Owner'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAddToShop',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='shops.Shop'),
        ),
    ]
