# Generated by Django 3.0.3 on 2020-03-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendences', '0005_auto_20200302_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
