# Generated by Django 3.0.3 on 2020-03-03 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendences', '0007_auto_20200303_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='office_entry_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendence',
            name='office_exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
