# Generated by Django 3.0.3 on 2020-03-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendences', '0008_auto_20200303_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='office_entry_time',
            new_name='entry_time',
        ),
        migrations.RenameField(
            model_name='attendence',
            old_name='office_exit_time',
            new_name='exit_time',
        ),
    ]
