# Generated by Django 3.0.3 on 2020-03-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendences', '0010_auto_20200304_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
