# Generated by Django 3.0.3 on 2020-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendences', '0012_auto_20200304_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='entry_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='is_approved',
            field=models.BooleanField(default=True, null=True, verbose_name='approval status'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
