# Generated by Django 3.0.3 on 2020-02-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
