# Generated by Django 3.0.3 on 2020-03-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200305_0033'),
        ('orders', '0005_auto_20200305_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderProduct', to='products.Product'),
        ),
    ]
