# Generated by Django 3.0.3 on 2020-02-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('products', '0004_auto_20200217_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.Shop'),
            preserve_default=False,
        ),
    ]
