# Generated by Django 3.0.3 on 2020-02-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200217_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='stock_quantity',
        ),
    ]
