# Generated by Django 3.0.3 on 2020-02-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200217_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_quantity',
            field=models.FloatField(),
        ),
    ]
